<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Add Customer Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.013">
  <properties />
            <testcase name="addCustomer" time="0.013" classname="com.sri.testcases.AddCustomerTest">
                <failure type="org.testng.internal.reflect.MethodMatcherException"
                  message="
Data provider mismatch
Method: addCustomer([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Raman,(java.lang.String) Arora,(java.lang.String) A234wd,(java.lang.String) Customer added successfully,(java.lang.String) Y]"
              >
<![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: addCustomer([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Raman,(java.lang.String) Arora,(java.lang.String) A234wd,(java.lang.String) Customer added successfully,(java.lang.String) Y]
  org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
  org.testng.internal.Parameters.injectParameters(Parameters.java:796)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
  org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
